components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      x-fern-bearer:
        name: apiKey
        env: SSOREADY_API_KEY

paths:
  /v1/saml/redeem:
    post:
      x-fern-sdk-group-name: saml
      x-fern-sdk-method-name: redeemAccessCode
      x-fern-examples:
        - request:
            samlAccessCode: saml_access_code_94d90b43a2027a9084bfc792
          response:
            body:
              email: john.doe@gmail.com
              organizationId: org_7cu5hsy9vrbi5d2k1qvbh19lj
              organizationExternalId: my_custom_external_id

  /v1/saml/redirect:
    post:
      x-fern-sdk-group-name: saml
      x-fern-sdk-method-name: getRedirectUrl
      x-fern-examples:
        - request:
            samlConnectionId: saml_conn_ac3bzzoqhaa88ozk29hhv12l
            organizationId: org_7cu5hsy9vrbi5d2k1qvbh19lj
          response:
            body:
              redirectUrl: https://your.redirect.url
