components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      x-fern-bearer:
        name: apiKey
        env: SSOREADY_API_KEY

paths:
  /v1/saml/redeem:
    post:
      x-fern-sdk-group-name: saml
      x-fern-sdk-method-name: redeemAccessCode

  /v1/saml/redirect:
    post:
      x-fern-sdk-group-name: saml
      x-fern-sdk-method-name: getRedirectUrl
